service: with-sls-v3
frameworkVersion: "3"

plugins:
  - serverless-typespec-generator

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  stage: dev

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          request:
            schemas:
              application/json: ${file(models/requests/create-user.json)}
          typespec:
            response:
              schemas:
                application/json:
                  "200": ${file(models/responses/create-user.json)}
                  "400": ${file(models/responses/error.json)}
                  "500": ${file(models/responses/error.json)}
